### ISSUE TITLE
can't use websocket with SSL

### ISSUE THREAD

**Issue by Suxsem** [remakeelectric/owrt_pub_feeds#7] opened 2015-02-21 19:01 UTC
Hi. I just installed mosquitto 1.4 on my openwrt router with Barrier breaker.
Without SSL i don't have any problem.
If I enable SSL support i got "failed: WebSocket opening handshake was canceled"

I'm testing websockets with http://www.hivemq.com/demos/websocket-client/
can you check please?

**Comment by karlp** [comment] 2015-02-21 19:14
No, you'll need to debug this further yourself.  I'm not using ssl websockets personally, I just make sure that mosquitto has ssl compiled, and that the flags for libwebsockets seemed correct.    Are you actually using a feed manually from this repository? or are you using the primary packages feed? https://github.com/openwrt/packages ?  

You'll need to check what version of libwebsockets got compiled and how.

**Comment by Suxsem** [comment] 2015-02-21 19:16
i just downloaded libwebsockets and mosquitto-1.4 compiled from trunk...
i understand that you are not using websockets...but could you please check?

**Comment by karlp** [comment] 2015-02-21 19:19
check what?

**Comment by Suxsem** [comment] 2015-02-21 19:20
if you can use hivemq.com/demos/websocket-client/ to connect to your broker with SSL

**Comment by Suxsem** [comment] 2015-02-21 19:20
and http_dir option of mosquitto-1.4 doesn't seem to work neither (with or without SSL)...

**Comment by karlp** [comment] 2015-02-21 19:26
http_dir works for me, and that's easy to test.  Are you sure you've built and installed the version you think you have?

**Comment by Suxsem** [comment] 2015-02-21 19:29
thanks for your test. when i enable http_dir i just get "sending ***" on mosquitto consolle but the browser receive a 0bytes response.
i'm using libwebsockets-openssl_1.3
and mosquitto_1.4
from https://downloads.openwrt.org/snapshots/trunk/brcm63xx/smp/packages/packages/
any advice?

**Comment by Suxsem** [comment] 2015-02-21 19:30
the only strange thing is that i'm getting postinst error when install them:

```
root@Sonny:~# opkg install http://downloads.openwrt.org/snapshots/trunk/brcm63xx/smp/packages/packages/libwebsockets-openssl_1.3-chrome37-firefox30-1_brcm63xx.ipk
Downloading http://downloads.openwrt.org/snapshots/trunk/brcm63xx/smp/packages/packages/libwebsockets-openssl_1.3-chrome37-firefox30-1_brcm63xx.ipk.
Installing libwebsockets-openssl (1.3-chrome37-firefox30-1) to root...
Configuring libwebsockets-openssl.
//usr/lib/opkg/info/libwebsockets-openssl.postinst: line 4: default_postinst: not found
Configuring mosquitto.
//usr/lib/opkg/info/mosquitto.postinst: line 4: default_postinst: not found
Collected errors:
 * pkg_run_script: package "libwebsockets-openssl" postinst script returned status 127.
 * opkg_configure: libwebsockets-openssl.postinst returned 127.
 * pkg_run_script: package "mosquitto" postinst script returned status 127.
 * opkg_configure: mosquitto.postinst returned 127.
```

**Comment by Suxsem** [comment] 2015-02-21 19:49
ok I finally got websocket + ssl support!
the problem was the self signed certificate... https://bugzilla.mozilla.org/show_bug.cgi?id=594502

now i'm investigating http_dir :)

**Comment by karlp** [comment] 2015-02-22 13:05
Glad it worked out :)

Just to be sure, you're not trying to install trunk snapshot binaries on a 14.07 Barrier Breaker device are you?  It might work sometimes, but it's certainly not recommended or supported.

**Comment by Suxsem** [comment] 2015-02-22 13:21
Yes, i am :D I know it's not recommended but I checked this particular packages and I didn't found any conflict with barrier breaker... And it's fully working :)

**Comment by Suxsem** [comment] 2015-02-23 08:15
hi @karlp ...
sorry for bother you again... but i'm still stuck with http_dir.
When i enable this option i can send a get request to the broker; the broker replay with the HTTP header but then it doesn't send the file requested.
In mosquitto output I can see "sending quested file..." but it doesn't actually send the file. This happens with or without ssl.
Can you suggest me something to try?

This is what i mean:

```
root@Sonny:~# telnet 127.0.0.1 1884
GET /ok.html HTTP/1.1
host: suxsem.dlinkddns.com

HTTP/1.0 200 OK
Server: mosquitto
Content-Length: 31

Connection closed by foreign host
```

**Comment by ralight** [comment] 2015-02-23 10:10
If your config file add "log_type websockets" and "websockets_log_level 255", then check the logs on the broker.

**Comment by karlp** [comment] 2015-02-23 12:46
Confirmed, 1.2 compat fixes break this somehow, at least for openwrt.
http://fpaste.org/189189/95552142/ is 1.4 release, failing
http://fpaste.org/189188/95539142/ is just before the 1.2 compat fixes, working.

**Comment by Suxsem** [comment] 2015-02-23 13:01
thanks for testing :) what can we do about this issue?

**Comment by ralight** [comment] 2015-02-23 14:51
Try this:

diff --git a/src/websockets.c b/src/websockets.c
index 95f8a81..cf2b5e7 100644
--- a/src/websockets.c
+++ b/src/websockets.c
@@ -72,7 +72,7 @@ struct libws_http_data {
        FILE *fptr;
 };

-#ifndef HTTP_STATUS_NOT_FOUND
+#ifndef LWS_FEATURE_SERVE_HTTP_FILE_HAS_OTHER_HEADERS_ARG
        /\* This is libwebsockets 1.2.x or earlier, we have to degrade our capabilities.
         \* Once lws 1.3 is widely available this should be removed. */
 #      define LWS_IS_OLD

**Comment by karlp** [comment] 2015-02-23 15:26
Fixed in this repo, as well as in openwrt itself: https://github.com/openwrt/packages/commit/7c2f386e2d67235f2f767f177802fa4d691230fc

**Closed as completed** 2015-02-23 15:26 UTC

**Comment by Suxsem** [comment] 2015-02-23 15:29
great, thanks :)
